type Props = { roles: string[] };

export function HelpPage({ roles }: Props) {
  const isTeacher = roles.includes("teacher");
  const isAdmin = roles.some((role) => ["school_admin", "district_admin", "platform_admin"].includes(role));

  return (
    <section className="panel help-page">
      <div className="section-heading compact"><div><p className="eyebrow">Pilot help</p><h2>Teacher Planning Platform help</h2><p className="supporting">Quick guidance for the weekly planning and administration workflows.</p></div></div>
      <div className="guidance-card"><strong>Data boundary</strong><p>TPP is for educator/account information, curriculum, standards, schedules, lesson plans, weekly reflection, and related professional planning content. Do not enter student names, IDs, grades, IEP/504 information, health or discipline information, identifiable student work, or other student-specific information. Use class- or group-level instructional observations.</p></div>

      {isTeacher && <section className="help-section"><h3>Teacher weekly workflow</h3><ol className="help-steps"><li><strong>Course Setup:</strong> Create each teaching section separately, confirm its meeting schedule, and add Curriculum & Pacing. Use the pacing format shown on screen or the Excel template.</li><li><strong>Friday validation:</strong> Load the current week and record what actually happened for every scheduled lesson. Choose whether missed or modified instruction should carry forward.</li><li><strong>Weekly Reflection / PLC Discussion:</strong> Complete all 12 district prompts yourself. Reflection is teacher-authored; use class- or group-level observations only.</li><li><strong>Build / reconcile the next week:</strong> Open Weekly plan, confirm schedule exceptions, build the curriculum week, and adjust the proposed teaching day when needed.</li><li><strong>Select standards:</strong> Choose from the approved authoritative standards mapped to the course. Save the selection before requesting planning assistance.</li><li><strong>Use AI planning assistance as needed:</strong> TPP may draft planning language from the governed curriculum and standards context. Review every suggestion and accept, edit, replace, or ignore it. AI does not replace teacher judgment.</li><li><strong>Review the working plan:</strong> Confirm Literacy Standards and ACT Preparation and edit any other planning fields that need teacher adjustment.</li><li><strong>Save, review PDFs, and submit:</strong> Save the draft, review the Instructional Planning Framework, Week at a Glance, Weekly Reflection / PLC Discussion, or Combined packet, then submit the weekly plan. Each class is submitted separately.</li></ol><div className="help-notes"><h3>Common teacher questions</h3><p><strong>My schedule changed.</strong> Add the schedule exception before rebuilding/reconciling the week.</p><p><strong>A lesson was not taught.</strong> Record that during Friday validation and select carry-forward when it should remain in sequence.</p><p><strong>I planned next week early.</strong> Friday validation still reconciles the actual current week before you finalize the next one.</p><p><strong>I changed a submitted plan.</strong> Save the revision and resubmit so administration sees the new immutable submitted revision.</p></div></section>}

      {isAdmin && <section className="help-section"><h3>Administrator workflow</h3><ol className="help-steps"><li><strong>Open Administration:</strong> Choose the reporting period needed for the operational summary.</li><li><strong>Review weekly submissions:</strong> Select the week, optionally filter by school, teacher, or course, and review Submitted, Revised after submission, and Not submitted records.</li><li><strong>Open the submitted plan:</strong> Select View submitted plan to review the exact immutable submitted revision as the Combined packet PDF.</li><li><strong>Download or print:</strong> Use the controls in the PDF review window when a copy is needed for normal administrative workflow.</li></ol><div className="help-notes"><h3>What administration is reviewing</h3><p>Administration reporting is limited to professional educator planning operations. A submitted revision is the teacher's immutable weekly submission for that class and week. If a teacher changes the plan after submission, the status identifies that a newer revision exists until the teacher resubmits.</p></div></section>}

      <section className="help-section"><h3>Pilot support checklist</h3><p>If something does not look right, first confirm the selected course and week, refresh or reopen the saved week, and note the exact action that produced the issue. Do not enter student information into a support description or screenshot.</p></section>
    </section>
  );
}
