type Props = { roles: string[] };

export function HelpPage({ roles }: Props) {
  const isTeacher = roles.includes("teacher");
  const isAdmin = roles.some((role) => ["school_admin", "district_admin", "platform_admin"].includes(role));

  return (
    <section className="panel help-page">
      <div className="section-heading compact"><div><p className="eyebrow">Pilot help</p><h2>Teacher Planning Platform help</h2><p className="supporting">Quick guidance for the weekly planning and administration workflows.</p></div></div>
      <div className="guidance-card"><strong>Data boundary</strong><p>TPP is for educator/account information, curriculum, standards, schedules, lesson plans, weekly reflection, and related professional planning content. Do not enter student names, IDs, grades, IEP/504 information, health or discipline information, identifiable student work, or other student-specific information. Use class- or group-level instructional observations.</p></div>

      {isTeacher && <section className="help-section"><h3>Teacher workflow</h3><div className="help-notes"><h3>First week</h3><p><strong>1. Add each class.</strong> From Dashboard, select Add course to open Course Setup. Confirm the class schedule, Curriculum & Pacing, and authoritative course standards mapping.</p><p><strong>2. Create and submit the first weekly lesson plan.</strong> Open Weekly plan, build/reconcile the week, select and save authoritative standards, use planning assistance if helpful, review/edit the working plan, save it, review or print the Instructional Planning Framework and Week at a Glance, and submit. Each class is a separate lesson-plan submission.</p></div><div className="help-notes"><h3>Every Friday after the first week</h3><p><strong>1. Close the current week.</strong> Open Friday validation for the week that was just taught. Record what actually happened and choose whether missed or modified instruction should carry forward.</p><p><strong>2. Complete the current week's reflection.</strong> Complete all 12 Weekly Reflection / PLC Discussion prompts yourself using class- or group-level observations only. The reflection belongs to the week that was just taught.</p><p><strong>3. Submit the completed current-week packet.</strong> Submit Friday closeout. TPP records a second immutable submission for that same week: the completed packet containing the already-submitted lesson plan, Week at a Glance, and the teacher-authored reflection.</p><p><strong>4. Build and submit the following week's lesson plan.</strong> TPP advances to the next week. Reconcile carry-forward lessons and schedule exceptions, select standards, complete/edit the plan, save, review or print the planning PDFs, and submit the following week's lesson plan. That plan remains separate from the prior week's completed packet.</p></div><div className="help-notes"><h3>Common teacher questions</h3><p><strong>I need to post next week's plan.</strong> After saving the following week's lesson plan, use its PDF controls to print the approved planning documents for posting.</p><p><strong>My schedule changed.</strong> Add the schedule exception before rebuilding/reconciling the week.</p><p><strong>A lesson was not taught.</strong> Record that during Friday validation and select carry-forward when it should remain in sequence.</p><p><strong>I planned next week early.</strong> Friday validation still closes the actual current week. Your already-prepared next-week lesson plan remains a separate submission.</p><p><strong>I changed a submitted lesson plan.</strong> Save the revision and resubmit so the upcoming lesson-plan record reflects the new immutable revision.</p></div></section>}

      {isAdmin && <section className="help-section"><h3>Administrator workflow</h3><ol className="help-steps"><li><strong>Open Administration:</strong> Choose the reporting period needed for the operational summary.</li><li><strong>Review weekly submissions:</strong> Select the week and optionally narrow the list by school, multiple teachers, or course.</li><li><strong>See both records:</strong> Each teacher/course row shows the pre-instruction <strong>Upcoming lesson plan</strong> and the end-of-week <strong>Completed weekly packet</strong> separately.</li><li><strong>Review one record:</strong> Open the lesson-plan submission to see the Instructional Planning Framework + Week at a Glance, or open the completed packet to see those documents plus the teacher reflection.</li><li><strong>Review many records:</strong> Choose Upcoming lesson plans or Completed weekly packets for bulk review, select individual rows or all filtered records, then review/download/print the selected immutable PDFs as one administrator packet.</li></ol><div className="help-notes"><h3>What administration is reviewing</h3><p>The upcoming lesson plan proves the plan was submitted before instruction. The completed weekly packet is a separate end-of-week record that attaches the teacher-authored reflection to that same week's plan. The following week's lesson plan appears under its own week and receives a completed packet only after that week's Friday closeout.</p></div></section>}

      <section className="help-section"><h3>Pilot support checklist</h3><p>If something does not look right, first confirm the selected course and week, refresh or reopen the saved week, and note the exact action that produced the issue. Do not enter student information into a support description or screenshot.</p></section>
    </section>
  );
}
