type Props = { roles: string[] };

export function HelpPage({ roles }: Props) {
  const isTeacher = roles.includes("teacher");
  const isAdmin = roles.some((role) => ["school_admin", "district_admin", "platform_admin"].includes(role));

  return (
    <section className="panel help-page">
      <div className="section-heading compact"><div><p className="eyebrow">Pilot help</p><h2>Teacher Planning Platform help</h2><p className="supporting">Quick guidance for the weekly planning and administration workflows.</p></div></div>
      <div className="guidance-card"><strong>Data boundary</strong><p>TPP is for educator/account information, curriculum, standards, schedules, lesson plans, weekly reflection, and related professional planning content. Do not enter student names, IDs, grades, IEP/504 information, health or discipline information, identifiable student work, or other student-specific information. Use class- or group-level instructional observations.</p></div>

      {isTeacher && <section className="help-section"><h3>Teacher workflow</h3><div className="help-notes"><h3>First week</h3><p><strong>1. Add each class.</strong> From Dashboard, select Add course to open Course Setup. Confirm the class schedule, Curriculum & Pacing, and authoritative course standards mapping.</p><p><strong>2. Create and submit the first weekly plan.</strong> Open Weekly plan, build/reconcile the week, select and save authoritative standards, use planning assistance if helpful, review/edit the working plan, save it, review or print the approved PDFs, and submit. Each class is a separate weekly submission.</p></div><div className="help-notes"><h3>Every Friday after the first week</h3><p><strong>1. Close the current week.</strong> Open Friday validation for the week that was just taught. Record what actually happened and choose whether missed or modified instruction should carry forward.</p><p><strong>2. Complete the current week's reflection.</strong> Complete all 12 Weekly Reflection / PLC Discussion prompts yourself using class- or group-level observations only. The reflection belongs to the week that was just taught.</p><p><strong>3. Finalize the current week.</strong> Submitting Friday closeout attaches the completed reflection to that same week's submitted lesson plan and creates the latest immutable submitted revision. The completed Combined packet therefore represents one finished week: that week's plan plus that week's reflection.</p><p><strong>4. Build the following week's plan.</strong> TPP advances to the next week. Reconcile carry-forward lessons and schedule exceptions, select standards, complete/edit the plan, save, review or print the PDFs, and submit the following week's lesson plan. This new plan does not receive a reflection until the following Friday.</p></div><div className="help-notes"><h3>Common teacher questions</h3><p><strong>I need to post next week's plan.</strong> After saving the following week's plan, use its PDF controls to print the approved planning document for posting.</p><p><strong>My schedule changed.</strong> Add the schedule exception before rebuilding/reconciling the week.</p><p><strong>A lesson was not taught.</strong> Record that during Friday validation and select carry-forward when it should remain in sequence.</p><p><strong>I planned next week early.</strong> Friday validation still reconciles the actual current week before the following week is finalized.</p><p><strong>I changed a submitted plan.</strong> Save the revision and resubmit so administration sees the new immutable submitted revision.</p></div></section>}

      {isAdmin && <section className="help-section"><h3>Administrator workflow</h3><ol className="help-steps"><li><strong>Open Administration:</strong> Choose the reporting period needed for the operational summary.</li><li><strong>Review weekly submissions:</strong> Select the week and optionally narrow the list by school, multiple teachers, or course.</li><li><strong>Select plans:</strong> Check individual submitted plans or use the header checkbox to select every submitted plan currently shown by the filters.</li><li><strong>Review one plan:</strong> Select View submitted plan to open that exact immutable submitted revision as the Combined packet PDF.</li><li><strong>Review many plans:</strong> Select Review selected PDFs to merge the selected immutable submissions into one administrative review PDF. Download or print the selected batch when needed.</li></ol><div className="help-notes"><h3>What administration is reviewing</h3><p>Before Friday closeout, the submitted record is that week's lesson plan. After Friday closeout, the latest submitted revision for that week includes the completed reflection as part of the Combined packet. The following week's plan is a separate submission and receives its own reflection at the end of that week.</p></div></section>}

      <section className="help-section"><h3>Pilot support checklist</h3><p>If something does not look right, first confirm the selected course and week, refresh or reopen the saved week, and note the exact action that produced the issue. Do not enter student information into a support description or screenshot.</p></section>
    </section>
  );
}
